### ISSUE TITLE
想请问是否有演示效果呢？

### ISSUE THREAD

**Issue by fubostudy** [Fucloud233/sysu-digital-man#1]

**Comment by Fucloud233** [comment]
如本仓库的README.md所言，本项目是在[Fay](https://github.com/TheRamU/Fay)开源数字人项目的基础上修改而成的，他们也有BiliBili的[官方账号](https://space.bilibili.com/2111554564)，所以演示效果可以参考他们的提供的视频。
我们这个修改后的项目，是用与参与学校的文创比赛，工期紧所以仍比较粗糙。相比于原项目而言，主要的改进是引入了向量数据库，重构了部分代码。当然我们也录制了[实机演示视频](https://www.jianguoyun.com/p/DU4yVJwQ6e6PDBjHy6MFIAA)，仅供参考。

**Comment by fubostudy** [comment]
好的，感谢大佬👍👍 还想请问一下 
1、UE5 工程文件是否可以分享？
2、这个交互延时还有点长，这个是否有优化的方向呢？
感谢！

**Comment by Fucloud233** [comment]
1. Fay团队提供了相关工程文件的[下载地址](https://www.bilibili.com/read/cv25133736/)，或者也可以咨询他们团队获取。
2. 现在数字人的主要延迟来自于a. LLM（大语言模型）处理 b. TTS（文本转语音）。两者都是采用了非流式传输，目前的的想法是通过流式传输来减少延迟，还是因为工期紧张，所以没有优化。保守估计最终优化的延迟可能也会在3-4s。

该项目内还缺少一些用于运行UE5的组件，不能对接UE5，但LLM和TTS部分还是能够正常运行。如果需要运行UE5部分，可以将联系方式发到我的邮箱(270928474@qq.com)，我会让负责这部分的相关同学帮忙协助。

目前我们学院成立了数字人项目组，主要目的是打造数字人主播，解决乡村缺少和难以培养带货主播的问题。项目组正处于起步阶段，也在积极地解决和优化目前该项目包括延迟在内的诸多问题。
